### ISSUE TITLE
woff and woff2 result in missing font on iOS

### ISSUE THREAD

**Issue by jnsprnw** [bubkoo/html-to-image#203]
I’m using `@font-face` to include a locally hosted font and I’m creating a blob.
When I only import `woff` and `woff2` files, the text used in the target `div` is simply left out on iOS.
I need to aditionally include the `ttf` file.

This might be related to #96.

### Possible Solution

The good thing is, that I can include all three formats for it to work:
```css
@font-face {
  font-family: 'FiraSans';
  font-style: normal;
  font-weight: 400;
  src: url('/fonts/FiraSans-Regular.woff2') format('woff2'),
       url('/fonts/FiraSans-Regular.woff') format('woff'),
       url('/fonts/FiraSans-Regular.ttf') format('truetype');
}
```
But it might be good to support other font formats as well.

#### EDIT (28.10.2021):
Unfortunately, I don’t have much time to dive in further for now, but I noticed that the first time the user saves the image, the text is still blank, even when I include the truetype font. What I do now, is that I render the image without downloading it the moment the element is mounted. When the user clicks to save the image, things are working as expected.

### Your Environment

- html-to-image: 1.9.0
- OS: iOS 15.1
- Browser: Firefox, Safari, Chrome
