### ISSUE TITLE
When using Transparent Color and Background, Nothing Renders

### ISSUE THREAD

**Issue by BrandonQDixon** [bubkoo/html-to-image#237]
### Expected Behavior

The image should render as it appears on the screen, such as:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/22106438/149639377-33cbb67d-8fe2-43a1-93c8-2058e8f9fbf2.png">

### Current Behavior

Nothing renders except for transparency:
![image](https://user-images.githubusercontent.com/22106438/149639381-85543b54-227c-4871-b5bd-46faaf0381df.png)

### Steps To Reproduce

1. Create a div and apply these css rules to it:
```css
#logo {
    color: transparent;
    background: linear-gradient(#3294cd, #a85c34);
    background-clip: text;
    -webkit-background-clip: text;
    font-style: italic;
    font-weight: bold;
    font-family: Aladin;
    filter:  brightness(100%) contrast(140%) saturate(140%);
}
```
2. Attempt to generate an image.

### Additional Context

I'm running this in an Angular project via npm install. I've successfully used this in other projects, but this is the first project where the text color is transparent and the background only is what is actually being displayed. I am running this on Chrome, Windows 11.
