### ISSUE TITLE
CSS counters are not correctly rendered

### ISSUE THREAD

**Issue by Mokkapps** [bubkoo/html-to-image#313]
### Expected Behavior

I use CSS counters:

```css
.line-numbers {
  code {
    counter-reset: step;
    counter-increment: step 0;
  }

  code .line::before {
    content: counter(step);
    counter-increment: step;
    width: v-bind(lineNumbersWidthPx);
    margin-right: v-bind(lineNumbersMarginRightPx);
    display: inline-block;
    text-align: right;
    color: $custom;
  }
}
```

and they are shown correctly before downloading the image: 

<img width="193" alt="image" src="https://user-images.githubusercontent.com/3127210/188127239-7883f042-84f4-41ca-b0f1-0f6f1203ec44.png">

### Current Behavior

Inside the generated image, the CSS counter value is 0 for every line:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/3127210/188127302-d8ec48d5-c998-4146-86a8-f18df5401744.png">

### Steps To Reproduce

1. Use https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters in any example
2. Download a image of that element

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- html-to-image: 1.10.8
- OS: macOS Montery 12.5.1
- Browser: Chrome Version 104.0.5112.101 (Official Build) (x86_64)
